# Backbone architectures for quantization experimentation
#for key in REGISTERED_BACKBONE_VERSIONS.keys(): print(key)

REGISTERED_BACKBONE_DESCRIPTIONS = {
    "baseline": "baselines of the backbone, everything in FP32 or everything quantized",
    "1": "Early trial experiments",
    "2": "Early trial experiments",
    "3": "Aggersive quantization - Lift one STAGE back to FP32 at a time.",
    "4": "Aggresive quantization - Lift one BLOCK TYPE back to FP32 at a time.",
    "5": "Aggresive quantization - SPARE one special thing back to FP32 at a time.",
    "6": "Soft quantization - one STAGE at a time",
    "7": "Soft quantization - one STAGE at a time, plus save bottleneck for that stage",
    "8": "Soft quantization - one BLOCK TYPE at a time",
    "9": "Soft quantization - one BLOCK TYPE at a time, plus save bottleneck if in those block types",
}

### Format: Model:Stage:Block:Layer
SIMPLE_REGISTERED_BACKBONE_VERSIONS = {
    'L0:x:x:x': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'block_position': [0,1,2,3,4,5,6,7,8,9],
        'layer_position': [0,1,2,3,4,5,6,7,8,9],
    },
    'L0:0:0:x': {
        'stages': ["stage0"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'block_position': [0],
        'layer_position': [0,1,2,3,4,5,6,7,8,9],
    },

}

REGISTERED_BACKBONE_VERSIONS = {
    # BASELINES
    'FP32_baseline': {
        'stages': [],
        'block_names': [],
        'spare_bottlenecks': True,
        'spare_attention_qkv': True,
        'spare_attention_scaling': True,
        'spare_attention_projection': True,
    },
    'INT8_baseline': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },

    ### Family ###
    '3_q_all_but_stage0': {
        'stages': ["unknown", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '3_q_all_but_stage1': {
        'stages': ["unknown", "stage0", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '3_q_all_but_stage2': {
        'stages': ["unknown", "stage0", "stage1", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '3_q_all_but_stage3': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '3_q_all_but_stage4': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '3_q_all_but_stage5': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '3_q_all_but_neck': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,

    },

    ### Family ###
    '4_q_all_but_ResBlocks': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '4_q_all_but_MBConvs': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '4_q_all_but_FusedMBConvs': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '4_q_all_but_Attention': { #should give same results as quantizing all but saving stage 4 + 5 - do check that it is the case!
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },

    ### Family ###
    '5_q_all_but_bottlenecks': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '5_q_all_but_attention_qkv': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': True,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '5_q_all_but_attention_scaling': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': True,
        'spare_attention_projection': False,
    },
    '5_q_all_but_attention_projection': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': True,
    },

    ### Family ###
    '6_q_only_stage0_spare_nothing': {
        'stages': ["stage0"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '6_q_only_stage1_spare_nothing': {
        'stages': ["stage1"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '6_q_only_stage2_spare_nothing': {
        'stages': ["stage2"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '6_q_only_stage3_spare_nothing': {
        'stages': ["stage3"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '6_q_only_stage4_spare_nothing': {
        'stages': ["stage4"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '6_q_only_stage5_spare_nothing': {
        'stages': ["stage5"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '6_q_only_neck_spare_nothing': {
        'stages': ["neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },

    ### Family ###
    '7_q_only_stage0_spare_bottlenecks': {
        'stages': ["stage0"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '7_q_only_stage1_spare_bottlenecks': {
        'stages': ["stage1"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '7_q_only_stage2_spare_bottlenecks': {
        'stages': ["stage2"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '7_q_only_stage3_spare_bottlenecks': {
        'stages': ["stage3"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '7_q_only_stage4_spare_bottlenecks': {
        'stages': ["stage4"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '7_q_only_stage5_spare_bottlenecks': {
        'stages': ["stage5"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '7_q_only_neck_spare_bottlenecks': {
        'stages': ["neck"],
        'block_names': ["independent", "res", "mb", "fmb", "att", "att@3", "att@5", "dag"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },

    ### Family ###
    '8_q_only_ResBlocks_spare_nothing': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["res"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '8_q_only_MBConvs_spare_nothing': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["mb"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '8_q_only_FusedMBConvs_spare_nothing': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["fmb"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '8_q_only_Attention_spare_nothing': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["att", "att@3", "att@5"],
        'spare_bottlenecks': False,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    
    ### Family ###
    '9_q_only_ResBlocks_spare_bottlenecks': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["res"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '9_q_only_MBConvs_spare_bottlenecks': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["mb"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '9_q_only_FusedMBConvs_spare_bottlenecks': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["fmb"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
    '9_q_only_Attention_spare_bottlenecks': {
        'stages': ["unknown", "stage0", "stage1", "stage2", "stage3", "stage4", "stage5", "neck"],
        'block_names': ["att", "att@3", "att@5"],
        'spare_bottlenecks': True,
        'spare_attention_qkv': False,
        'spare_attention_scaling': False,
        'spare_attention_projection': False,
    },
}
